# Example Fighter Jet SDK Configuration

# Global settings
log_level: INFO
log_file: ./logs/fighter_jet_sdk.log
data_directory: ./data
parallel_processing: true
max_threads: 8
cache_enabled: true
cache_size_mb: 2048

# Simulation settings
simulation_precision: double
max_iterations: 5000
convergence_tolerance: 1e-8

# Engine-specific configurations
engines:
  design:
    module_library_path: ./modules
    validation_strict: true
    auto_optimize: true
    
  materials:
    database_path: ./data/materials.db
    simulation_precision: high
    frequency_points: 2000
    temperature_points: 500
    
  propulsion:
    cfd_solver: openfoam
    thermal_analysis: true
    optimization_enabled: true
    max_thrust_iterations: 1000
    
  sensors:
    atmospheric_model: standard
    noise_modeling: true
    multi_target_tracking: true
    radar_frequency_bands: [2.0e9, 10.0e9, 35.0e9]  # S, X, Ka bands
    
  aerodynamics:
    cfd_mesh_density: high
    turbulence_model: k-omega-sst
    compressibility_effects: true
    mach_range: [0.1, 5.0]
    
  manufacturing:
    cost_database_path: ./data/costs.db
    quality_standards: aerospace
    optimization_method: genetic_algorithm
    production_volume: 100

# Security settings
encryption_enabled: false
access_control_enabled: false

# Backup settings
backup_enabled: true
backup_interval_hours: 12